# Window rules (see docs/user/window-rules.md) ---------------------------

[[window_rule]]
match.app_id = "brave-browser"
match.at_startup = true
default_workspace = 1

[[window_rule]]
match.app_id = "discord"
match.at_startup = true
default_scrolling_column_order = 0
default_scrolling_column = "twin"
default_workspace = 1

[[window_rule]]
match.app_id = "kitty"
match.at_startup = true
default_scrolling_column_order = 1
default_scrolling_column = "twin"
default_workspace = 1

[[window_rule]]
match.app_id = "spotify|steam|heroic|org.prismlauncher.PrismLauncher"
default_workspace = 2

[[window_rule]]
match.app_id = "steam"
match.title = "^(?!Steam$).*$"
default_floating = true

[[window_rule]]
match.app_id = "^steam_app_[0-9]+$|gamescope"
default_fullscreen = true
default_focused = false
default_workspace = 3

[[window_rule]]
match.app_id = "org.vinegarhq.Sober|Minecraft|Cleanroom"
default_maximize = true
default_focused = false
default_workspace = 3

[[window_rule]]
match.title = "Picture-in-[Pp]icture|Discord Popout"
default_floating = true
default_pinned = true
default_position = { x = 4, y = 4, anchor = "top_right" }
default_size = [960, 540]

[[window_rule]]
match.app_id = "^dev.noctalia.Noctalia$"
default_floating = true
default_size = [1020, 900]

[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = true
default_size = [800, 600]

# Layer rules (see docs/user/layer-rules.md) ---------------------------

