[mgr]

show_hidden    = false

[opener]                                                                                                                                                              
edit = [
    { run = "${EDITOR:-vim} %s", desc = "$EDITOR",      for = "unix", block = true },
]

